import { useKeycloak } from '@react-keycloak/ssr'
import type { NextPage } from 'next'
import Head from 'next/head'
import CreatePost from './timeline/CreatePost'
import { ParsedToken } from '../Types/Token'


const Home: NextPage = () => {
  const { keycloak } = useKeycloak()
  const parsedToken: string | undefined = keycloak?.token

  const welcomeMessage =
    keycloak?.authenticated || (keycloak && parsedToken)
      ? "you are logged in"
      : "Welcome visitor. Please login to continue.";
  return (
    <div className="">
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet"></link>
      </Head>

      <CreatePost />

      <main className="">
        <h1 className="">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="">
          {welcomeMessage}
        </p>
      </main>
    </div>
  )
}

export default Home
